export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  WAREHOUSE_DISABLED: "WAREHOUSE_DISABLED",
  INSUFFICIENT_BATCH_STOCK: "INSUFFICIENT_BATCH_STOCK",
  BELOW_SAFETY_STOCK: "BELOW_SAFETY_STOCK",
  FORCE_REASON_REQUIRED: "FORCE_REASON_REQUIRED",
  ORDER_STATUS_INVALID: "ORDER_STATUS_INVALID",
  EMPTY_DISPATCH_LINES: "EMPTY_DISPATCH_LINES"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
