server.port=8080
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=Asia/Shanghai
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
